# Generated by Django 3.1.7 on 2021-04-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210325_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(default='message here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='title here', max_length=50),
        ),
    ]
