# Generated by Django 3.1.7 on 2021-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
