# Generated by Django 3.1.7 on 2021-04-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_num_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default='put JSONobject here', max_length=50000),
        ),
    ]
