# Generated by Django 3.1.7 on 2021-04-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TextField(max_length=500),
        ),
    ]
