# Generated by Django 3.1.7 on 2021-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='post',
        ),
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.TextField(default='message here', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='num_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='num_of_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='num_of_upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(default='title here', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TextField(max_length=500),
        ),
    ]
