# Generated by Django 3.1.7 on 2021-04-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210424_1531'),
        ('posts', '0010_auto_20210424_1612'),
    ]

    operations = [
    ]
