# Generated by Django 3.1.7 on 2021-04-24 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='title here', max_length=50)),
                ('message', models.TextField(default='message here', max_length=1000)),
                ('num_of_upvotes', models.IntegerField(default=0)),
                ('num_of_downvotes', models.IntegerField(default=0)),
                ('num_of_comments', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('start_time', models.TextField(max_length=500)),
                ('end_time', models.TextField(max_length=500)),
                ('exact_location', models.TextField(default='{"latitude":40.344149988101236,"longitude":-74.65598258598506}', max_length=50000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
