# Generated by Django 3.1.7 on 2021-04-28 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_event'),
        ('posts', '0011_merge_20210426_2158'),
    ]

    operations = [
    ]
