# Generated by Django 3.1.7 on 2021-04-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_comment_is_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='message',
        ),
        migrations.RemoveField(
            model_name='event',
            name='num_of_comments',
        ),
        migrations.RemoveField(
            model_name='event',
            name='num_of_downvotes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='num_of_upvotes',
        ),
        migrations.RemoveField(
            model_name='event',
            name='score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='posts.post'),
        ),
    ]
