# Generated by Django 3.1.7 on 2021-04-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210402_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='description here', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(default='title here', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.TextField(default='full name here', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(default='put JSONobject here', max_length=50000),
        ),
    ]
