# Generated by Django 3.1.7 on 2021-04-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20210403_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='location',
            field=models.TextField(default='no channel location inserted from html', max_length=50000),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.TextField(default='title here', max_length=50, unique=True),
        ),
    ]
